SELECT IF(GRADES.GRADE>=8,STUDENTS.NAME,NULL),GRADES.GRADE,STUDENTS.MARKS FROM STUDENTS 
JOIN GRADES WHERE MARKS BETWEEN MIN_MARK AND MAX_MARK 
ORDER BY GRADE DESC, 
CASE 
WHEN NAME IS NOT NULL THEN NAME
ELSE MARKS 
END ASC;